CREATE TABLE roles (
  id        int GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,   -- Автоинкрементируемый первичный ключ
  name      TEXT NOT NULL            -- Название роли
);

CREATE TABLE users (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- Автоинкрементируемый первичный ключ
    email     TEXT UNIQUE,    -- Уникальный email
    phone     TEXT UNIQUE,    -- Уникальный номер телефона
    pass_hash BYTEA NOT NULL,           -- Пароль в виде хэша (байты)
    role_id   int REFERENCES roles(id)
);

CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_phone ON users(phone);

CREATE TABLE apps (
  id        int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,   -- Автоинкрементируемый первичный ключ
  name      TEXT NOT NULL UNIQUE,           -- Название приложения
  secret    TEXT NOT NULL            -- Секретное слово приложения
);

CREATE INDEX idx_apps_name ON apps(name);

INSERT INTO roles (id, name) VALUES (1, 'admin');
INSERT INTO roles (id ,name) VALUES (2, 'user');