name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Можно изменить на нужную ветку
    tags:
      - v* # Публиковать образ при создании тега вида v1.0.0

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Логинимся в Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # 4. Устанавливаем Buildx (для оптимизированного билда)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 5. Получаем версию из тега
      - name: Extract tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
        shell: bash

      # 5. Собираем и пушим Docker-образ
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./sso
          file: ./sso/Dockerfile # Укажите путь, если Dockerfile в другом месте
          push: true
          tags: |
            almasnurbayev/learn_go_grpc_sso:latest
            almasnurbayev/learn_go_grpc_sso:${{ env.VERSION }}
